<?php

namespace Database\Seeders;

use App\Models\Registrant;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;


class RegistrantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $registrants = [
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Roy ward castillo ','email' => 'roywardcastillo@gmail.com','gender' => 'Male','company' => 'LDR Events Solution','company_address' => 'Angono rizal','position' => 'Operations Manager ','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '09067950522','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 11, 34)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Jocelyn P. Lim','email' => 'jplim08@gmail.com','gender' => 'Female','company' => 'Women in Infrastructure Foundation Inc','company_address' => 'Pasig','position' => 'President','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178586233','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 9, 11, 11, 10)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Aj Paalisbo','email' => 'ajae.nueca@gmail.com','gender' => 'Female','company' => 'LDR Events Solution','company_address' => 'Angono, Rizal','position' => 'Technical Staff','affiliation' => 'Event Organizer','contact_number' => '09183924854','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 15, 43)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Maricel Belista','email' => 'macegabz17@gmail.com','gender' => 'Female','company' => 'LDR Events Solution','company_address' => 'Taytay Rizal','position' => 'Project Coordinator','affiliation' => 'Management Services','contact_number' => '0985 889 5229','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 15, 50)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Luis Angelo Sevilla','email' => 'luisangelo.sevilla@gmail.com','gender' => 'Male','company' => 'F.R. Sevilla Industrial and Development Corp','company_address' => 'Sevilla bldg., ARTY 2 St., Talipapa, Novaliches, QC','position' => 'President','affiliation' => 'PSVARE','contact_number' => '09188186983','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 6)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Ofelia R. Usigan','email' => 'ofeliausigan@construction.gov.ph','gender' => 'Female','company' => 'Construction Manpower Development Foundation (CMDF)','company_address' => 'Makati City','position' => 'Executive Director','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09154004065','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 16)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Ronald Magsajo','email' => 'president@philippineironsteel.org','gender' => 'Male','company' => 'Philippine Iron and Steel Institute','company_address' => 'Suite 509 Citiland Shaw Tower, Shaw Blvd. Mandaluyong City','position' => 'President','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09175757514','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 30)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Doris Gacho','email' => 'DorisGacho@construction.gov.ph','gender' => 'Female','company' => 'CIAP-PODCB','company_address' => '5th Flr., Executive Center Bldg., Makati Ave. Cor. Sen. Puyat, Makati City','position' => 'Executive Director','affiliation' => 'CIAP-PODCB','contact_number' => '09178796765','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 20)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Dr.','name' => 'Fiorello R ESTUAR','email' => 'frestuar@estuar.net','gender' => 'Male','company' => 'PCA, GPPB','company_address' => 'FR ESTUAR & ASSOCIATES ESTUAR BLDG 880 QUEZON AVENUE, QC','position' => 'CHAIRMAN/PRESIDENT','affiliation' => 'GPPB','contact_number' => '0920 920 8175','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 23)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Roberto S. Genato','email' => 'genato.bobby@mdc.com.ph','gender' => 'Male','company' => 'Makati Development Corporation','company_address' => 'Radian Street, Arca South, Taguig City','position' => 'HR Manager','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09175135324','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 33)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Arch.','name' => 'Lesley Villanueva','email' => 'levillanueva@datem.com.ph','gender' => 'Female','company' => 'Philippine Constructors Association','company_address' => 'DATEM Building 99 Mindanao Avenue, Quezon City','position' => 'President','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09209555581','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 11, 11, 16, 36)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Marcelino Mendoza','email' => 'mcmendoza02@yahoo.com','gender' => 'Male','company' => 'OSHDP','company_address' => 'Greenhills, San Juan','position' => 'Chairman of the Board','affiliation' => 'OSHDP','contact_number' => '+639209665506','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 1, 11, 16, 41)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Victor P. Lazatin','email' => 'vplazatin@accralaw.com','gender' => 'Male','company' => 'ACCRALAW Offices','company_address' => '22/F ACCRALAW Tower, 2nd Avenue cor. 30th Street, Crescent Park West, BGC, Taguig','position' => 'Senior Legal Counsel','affiliation' => 'Philippine Dispute Resolution Resolution Center, Inc.','contact_number' => '09175320285','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 1, 11, 16, 49)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Alec S. Ladanga','email' => 'chiefofstaff@philippineconstructors.org','gender' => 'Male','company' => 'Philippine Constructors Assocation, Inc.','company_address' => 'chiefofstaff@philippineconstructors.org','position' => 'Chief of Staff','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178080944','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 1, 11, 17, 9)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Vincent H. Medina','email' => 'medina.vince@mdc.com.ph','gender' => 'Male','company' => 'Makati Development Corporation','company_address' => 'MDC Corporate Center, Arca South, Taguig City','position' => 'Vice President','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178322110','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 12, 11, 9, 3)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'RAMON O. FERNANDO','email' => 'office.pcametro@gmail.com','gender' => 'Male','company' => 'PCA METROPOLITAN CHAPTER INC.','company_address' => '700 ROAD 1 OLD BALARA QUEZON CITY','position' => 'PRESIDENT','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09175858885','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 12, 11, 12, 14)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Einstein Chiu','email' => 'eochiu@firstbalfour.com','gender' => 'Male','company' => 'First Balfour','company_address' => 'Sucat, Parañaque','position' => 'AVP & GM for Concrete & Aggregates Division','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178144485','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 12, 11, 18, 41)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Roberto S. Genato','email' => 'genato.bobby@mdc.com.ph','gender' => 'Male','company' => 'Makati Development Corporation','company_address' => 'Radian Street, Arca South, Taguig City','position' => 'HR Manager','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09175135324','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 11, 21)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Dr.','name' => 'ABSALITA C. TEVES','email' => 'abcteves123@gmail.com','gender' => 'Female','company' => 'Contractors Association of Negros Oriental, Inc. /RACCT CONSTRUCTION AND TRADING','company_address' => 'Dumaguete City/ Poblacion, Sibulan, Negros Oriental','position' => 'PCA-CANOI, Past President/ AMO & Proprietor','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09190079168','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 16, 48)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Dodjie Aumentado','email' => 'daumentado@worldbank.org','gender' => 'Male','company' => 'World Bank','company_address' => '26th Floor One Global Place, 5th Avenue, BGC, Taguig','position' => 'Senior Procurement Specialist/Hub Coordinator for Philippines, Malaysia and Brunei','affiliation' => 'International Procurement Practitioner','contact_number' => '+1 202 361 9990','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 18, 53)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Jocelyn P. Lim','email' => 'jplim08@gmail.com','gender' => 'Female','company' => 'RSP Lim Construction Co. Inc','company_address' => 'The Boni Tower, Boni Ave., Mandaluyong City','position' => 'Vice President','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178586233','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 13, 11, 19, 1)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Arthur N. Escalante','email' => 'anescalante@yahoo.com','gender' => 'Male','company' => 'AN Escalante Construction, Inc.','company_address' => 'ANECI Bldg., Goyengko Drive, Nacilla Village, Bugac Maa, Davao City','position' => 'President','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09189053930','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 9, 15)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'MARIA GUDELIA CACDAC GUESE','email' => 'gguese@pitc.gov.ph','gender' => 'Female','company' => 'Philippine International Trading Corporation','company_address' => 'NDC BUILDING, 116 TORDESILLAS ST., SALCEDO VILLAGE, MAKATI CITY','position' => 'OFFICER-IN-CHARGE, OFFICE OF THE PITC PRESIDENT','affiliation' => 'NONE','contact_number' => '09178483354','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 9, 54)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'MYRA CHITELLA T. ALVAREZ','email' => 'myra-chitella@pitc.gov.ph','gender' => 'Female','company' => 'Philippine International Trading Corporation','company_address' => 'NDC BUILDING, 116 TORDESILLAS ST., SALCEDO VILLAGE, MAKATI CITY','position' => 'OIC - VP, PROCUREMENT OUTSOURCING SERVICES GROUP','affiliation' => 'NONE','contact_number' => '09178214965','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 9, 57)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Jerome A. Matas','email' => 'jerome.matas@gmail.com','gender' => 'Male','company' => 'CIAC','company_address' => '2nd Floor Executive Building Center, 369 Sen Gil Puyat Ave cor Makati Ave. Makati City','position' => 'Executive Director','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09177075920','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 10, 18)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Roderick Planta','email' => 'oasec.infradevelopment@gmail.com','gender' => 'Male','company' => 'National Economic and Development Authority','company_address' => '32F, Infrastructure Development Office, Neda, The Mega Tower, Wack Wack Greenhills','position' => 'Assistant Secretary','affiliation' => 'NEDA','contact_number' => '09163679720','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 10, 53)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Maresher Dela Cruz','email' => 'maresherdelacruz@gmail.com','gender' => 'Female','company' => 'T2B3 Builders and Suppliers Inc','company_address' => 'Tarlac','position' => 'Project Engineer','affiliation' => 'SCLP','contact_number' => '09605269910','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 10, 56)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Elizabeth L. Policarpio','email' => 'shabaltero1995@gmail.com','gender' => 'Female','company' => 'Philippine Ports Authority (Port Construction and Maintenance Department)','company_address' => 'Bonifacio Drive, South Harbor, Port Area, Manila','position' => 'Division Manager A','affiliation' => 'Government Agency','contact_number' => '09173223838','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 11, 30)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'PERGENT VAN A. ARPON','email' => 'gladicegaspan2210@gmail.com','gender' => 'Male','company' => 'Philippine Ports Authority','company_address' => 'PPA Corporate Bldg., Bonifacio Drive, South Harbor','position' => 'Division Manager, CMD-Luzon','affiliation' => 'Government Agency','contact_number' => '09178951276','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 11, 48)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'GILBERT','email' => 'gibma2003@yahoo.com','gender' => 'Male','company' => 'GIBMA ENGINEERING SERVICES / SCLP','company_address' => 'PASIG CITY','position' => 'GENERAL MANAGER','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '09209226441','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 11, 58)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Lourdes J. Espinosa','email' => 'lourdes.espinosa@gmail.com','gender' => 'Female','company' => 'Philippine Institute of Construction Arbitrators and Mediators  Inc.','company_address' => 'Makati City','position' => 'Vice President','affiliation' => 'Philippine Institute of Construction Arbitrators and Mediators Inc.','contact_number' => '09209044720','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 15, 56)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Sharon Gay B. Pascual','email' => 'sha_pascual@yahoo.com.ph','gender' => 'Female','company' => 'Society of Construction Law','company_address' => 'Makati City','position' => 'Council Member','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09054940320','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 14, 11, 22, 03)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'John Jowhell H. Villegas','email' => 'johnjowhell.villegas@aitech.edu.ph','gender' => 'Male','company' => 'Antipolo Institute of Technology','company_address' => 'Antipolo City','position' => 'Associate Professor V / College Dean','affiliation' => 'Antipolo Institute of Technology','contact_number' => '09958606771','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 15, 11, 11, 42)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Dr.','name' => 'Aileen A. Diansuy','email' => 'aileen.diansuy@aitech.edu.ph','gender' => 'Female','company' => 'Antipolo Institute of Technology','company_address' => 'Antipolo City','position' => 'Interim President','affiliation' => 'Antipolo Institute of Technology','contact_number' => '09958606771','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 15, 11, 11, 43)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Arch.','name' => 'Cecilia Cayman-Gamana, UAP, AA.,APEC AR','email' => 'archccg@yahoo.com','gender' => 'Female','company' => 'UNITED ARCHITECTS OF THE PHILIPPINES','company_address' => '1103 53 Sct. Rallos St, Diliman, Quezon City, 1103 Metro Manila','position' => 'Executive Director, Commission on Professional Practice','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '9178212126','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 15, 11, 13, 30)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Arch.','name' => 'Vienna Jessica C. Manalo','email' => 'jica.manalo@peza.gov.ph','gender' => 'Female','company' => 'Philippine Economic Zone Authority','company_address' => '10th Floor, DoubleDragon Center West Building, Macapagal Avenue, Pasay City','position' => 'Architect','affiliation' => 'United Architects of the Philippines','contact_number' => '09273060071','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 18, 11, 9, 10)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Lord Louis P. Valera','email' => 'assistant.commissioner@prc.gov.ph','gender' => 'Male','company' => 'Professional Regulation Commission','company_address' => 'P. Paredes St. cor. N. Reyes, Sampaloc Manila','position' => 'Assistant Commissioner','affiliation' => 'Government Agency','contact_number' => '09667366900','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 19, 11, 11, 58)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Melody Dionisio','email' => 'ifawpca.secretariat@gmail.com','gender' => 'Female','company' => 'IFAWPCA Inc.','company_address' => '3rd Flr. Padilla Bldg. F. Ortigas Jr. Road Ortigas Center Pasig City','position' => 'Operations Manager','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '+63 9174982172','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 20, 11, 13, 45)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Melody Dionisio','email' => 'ifawpca.secretariat@gmail.com','gender' => 'Female','company' => 'IFAWPCA Inc.','company_address' => '3rd Flr. Padilla Building F. Ortigas Jr. Road Ortigas Center Pasig City','position' => 'Operations Manager ','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '09174982172','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 10, 59)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Augusto Manalo','email' => 'lrvillaflores@jemanalo.com','gender' => 'Male','company' => 'CIAP Board','company_address' => '1188 Bernal St., Cor C. Raymundo Ave., Rosario, Pasig City','position' => 'Board Member','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09175314788','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 13, 39)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Manuel M. Bonoan','email' => 'bonoan.manuel@dpwh.gov.ph','gender' => 'Male','company' => 'Department of Public Works & Highways','company_address' => 'DPWH Head Office, Bonifacio Drive, Port Area, Manila','position' => 'Department Secretary','affiliation' => 'DPWH','contact_number' => '09159984799','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 14, 31)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Dr.','name' => 'David Klebs ','email' => 'wi-1@mani.diplo.de','gender' => 'Male','company' => 'German Embassy','company_address' => 'RCBC Tower','position' => 'Economic Counsellor','affiliation' => 'Embassy','contact_number' => '09176319454','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 14, 40)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Loreto G. Catalan','email' => 'catalan.loreto@yahoo.com.ph','gender' => 'Male','company' => 'PHIL SOCIETY OF MECHANICAL ENGINEERS INC','company_address' => '19 Scout Bayoran, Bgy South Triangle Quezon City','position' => 'Immediate Past President','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09178031347','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 16, 19)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Lourdes J. Espinosa','email' => 'lourdes.espinosa@gmail.com','gender' => 'Female','company' => 'PICAM','company_address' => 'Makati City','position' => 'Vice President','affiliation' => 'Phil Institute of Construction Arbitrators and Mediators Inc.','contact_number' => '09209044720','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 16, 22)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Darcy Lae S. Aguilar','email' => 'DarcyLaeAguilar@dti.gov.ph','gender' => 'Female','company' => 'Department of Trade and Industry','company_address' => 'Makati City','position' => 'TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09176202646','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 16, 42)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Melanie Banayos','email' => 'mpbanayos@bwc.dole.gov.ph','gender' => 'Female','company' => 'DOLE - Bureau of Working Conditions','company_address' => 'Intramuros, Manila','position' => 'Supervising Labor and Employment Officer','affiliation' => 'DOLE - Bureau of Working Conditions','contact_number' => '09776412887','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 16, 53)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Rodgerson Dy','email' => 'rodger@trends.com.ph','gender' => 'Male','company' => 'Trends & Technologies, Inc. ','company_address' => 'Trafalgar Plaza, 105 HV Dela Costa St. Salcedo Village, Makati City','position' => 'Business Unit Head','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09175269141','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 18, 51)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Nicole -Cate C. Jop','email' => 'jopnicca@gmail.com','gender' => 'Female','company' => 'Professional Regulation Commission ','company_address' => 'P. Paredes St. cor. Nicanor Reyes St. Morayta Manila','position' => 'Administrative Aide VI','affiliation' => 'Government','contact_number' => '09667366900','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 21, 11, 20, 44)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Danilo Cariño ','email' => 'dbcarino@gmail.com','gender' => 'Male','company' => 'Premium Apartments Developers Corp ','company_address' => 'Chaffee st. Moonwalk Village Ph2 Paranaque City ','position' => 'President ','affiliation' => 'CIAC','contact_number' => '09228095850','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 7, 30)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Dr.','name' => 'MARIA CATALINA E. CABRAL','email' => 'cabral.ma_catalina@dpwh.gov.ph','gender' => 'Female','company' => 'DPWH','company_address' => 'Bonifacio Drive, Port Area, Manila','position' => 'Undersecretary','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09276066849','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 7, 46)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Rayeesha Villafuerte','email' => 'ysha.villafuerte@uli.org','gender' => 'Female','company' => 'ULI Philippines','company_address' => 'Penthouse, De Le Salle University, Rufino Campus, University Pkwy, Taguig, 1634 Metro Manila','position' => 'Project Assistant','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09053156979','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 9, 31)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Divine Duran','email' => 'divine.duran@uli.org','gender' => 'Female','company' => 'ULI Philippines','company_address' => 'Penthouse, De Le Salle University, Rufino Campus, University Pkwy, Taguig, 1634 Metro Manila','position' => 'Executive Director','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '0917 538 5220','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 9, 33)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Simeon P. Perez','email' => 'sammypp1956@gmail.com','gender' => 'Male','company' => 'Philippine Society of Mechanical Society, Inc.','company_address' => '19 Sct Bayoran, Bgy South Triangle','position' => 'Executive Vice President','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09173242507','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 10, 43)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Moira Lintongan Idiesca','email' => 'moira.idiesca@dmw.gov.ph','gender' => 'Female','company' => 'Department of Migrant Workers','company_address' => 'Ortigas Avenue corner EDSA, Mandaluyong City','position' => 'Officer-in-Charge','affiliation' => 'government','contact_number' => '09175006269','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 12, 29)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Apple Marie C. Vitug','email' => 'acvitug@neda.gov.ph','gender' => 'Female','company' => 'National Economic and Development Authority','company_address' => '32nd floor Megatower, Mandaluyong City','position' => 'Senior Economic Development Specialist','affiliation' => 'NEDA','contact_number' => '09166390830','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 14, 4)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Ronaldo R. Elepano, Jr.','email' => 'rrelepano@gmail.com','gender' => 'Male','company' => 'D.M. Consunji, Inc.','company_address' => 'DMCI Plaza Building, 2281 Chino Roces Avenue Extension,Makati City 1231','position' => 'Sr. Adviser for Business Development','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09175396309','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 16, 12)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Maria Elena Go Francusco','email' => 'atty_ellenfrancisco@yahoo.com','gender' => 'Female','company' => 'Philippine Constructors Association, Inc,','company_address' => '3rd Floor, Padilla Bldg. F. Ortigas, Jr. Rd. Ortigas Center, Pasig City','position' => 'Corporate Secretary and Legal Counsel','affiliation' => 'Women in Infrastructure Foundation, Inc.','contact_number' => '09178332226','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 19, 2)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Natalie Pardo-Labang','email' => 'nat.pardo.labang@gmail.com','gender' => 'Female','company' => 'CIAP','company_address' => 'Makati City','position' => 'Division Chief','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09613622703','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 22, 11, 21, 46)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Roger G. Antonio','email' => 'rantonio@spcastro.com','gender' => 'Male','company' => 'SPCastro, Inc,','company_address' => '6F The Linden Suites, Ortigas Center, Pasig City','position' => 'Sr, VP/Director','affiliation' => 'PICAM Member','contact_number' => '09178815596','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 9, 29)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Justice Teresita V. Diaz-Baldos','email' => 'jtvdbaldos@gmail.com','gender' => 'Female','company' => 'Construction Industry Arbitration Commission','company_address' => '2nd Floor Executive Bldg. Center, #369 Gil J. Puyat Ave. cor. Makati Ave., Makati City','position' => 'Chairperson','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09178972246','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 9, 38)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Gia veloso','email' => 'Tech7.geoprojectinc@gmail.com','gender' => 'Female','company' => 'Teresa marble corp ','company_address' => 'Pasig','position' => 'Consultant','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '0917 5836685 ','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 6)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Paula tolentino','email' => 'Tech7.geoprojectinc@gmail.com','gender' => 'Female','company' => 'Geoprojects inc ','company_address' => 'Qc','position' => 'Consultant','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09399232589','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 9)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'LIBERITO ESPIRITU','email' => 'lvespiritu@datem.com.ph','gender' => 'Male','company' => 'DATEM INC.','company_address' => '99 MINDANAO AVE. DATEM BLDG. BRGY. BAHAY TORO, QUEZON CITY ','position' => 'CHAIRMAN','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '09175207558','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 11)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'LESLEY ARDELLE VILLANUEVA','email' => 'levillanueva@datem.com.ph','gender' => 'Female','company' => 'DATEM INC.','company_address' => '99 MINDANAO AVE. DATEM BLDG. BRGY. BAHAY TORO, QUEZON CITY','position' => 'PRESIDENT','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09178280129','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 13)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Maria Elena Francisco','email' => 'atty.ellenfrancisco@gmail.com','gender' => 'Female','company' => 'PCA','company_address' => '3/F Padilla Bldg, 1605 F. Ortigas Jr. Rd, Ortigas Center, Pasig, Metro Manila','position' => 'Corporate Secretary','affiliation' => 'International Federation of Asian and Western Pacific Contractors’ Associations, Inc. (IFAWPCA Inc.)','contact_number' => '09178332226','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 45)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Alanie Diaz','email' => 'alanie.diaz@aboitiz.com','gender' => 'Female','company' => 'Aboitiz Construction, Inc.','company_address' => 'NAC tower BGC','position' => 'Senior Manager','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09176339713','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 10, 58)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Levi Agoncillo','email' => 'levi.agoncillo@aboitiz.com','gender' => 'Male','company' => 'Aboitiz Construction ','company_address' => 'NAC TOWER BGC','position' => 'Vice President for Business Development ','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09175264836','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 11, 1)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Marcelius Cardona','email' => 'marcelius.cardona@aboitiz.com','gender' => 'Male','company' => 'ABOITIZ CONSTRUCTION','company_address' => 'Nac tower BGC','position' => 'AVP - Business Development ','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09171330832','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 11, 2)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Maria Consuelo J. Fernandez','email' => 'm.fernandez@acubetic.com','gender' => 'Female','company' => 'PT ACube TIC International','company_address' => '9th Floor Filinvest One Bldg. Alabang Zapote Road, Alabang Muntinlupa City','position' => 'ISO Admin Officer','affiliation' => 'Certification Body','contact_number' => '09182096845','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 11, 9)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Connie G. Pabalan','email' => 'c.pabalan@acubetic.com','gender' => 'Female','company' => 'PT Acube TIC International','company_address' => '9th Floor, c/o Regus, Filinvest One Building, Alabang Zapote Road','position' => 'Marketing Specialist','affiliation' => 'Certification Body','contact_number' => '09053375022','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 11, 9, 54)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Monaliza C. Fabrigar','email' => 'fabrigarmonaliza@gmail.com','gender' => 'Female','company' => 'Richbuild Construction Corporation','company_address' => 'C6 Road Barangay Wawa Taguig City','position' => 'Quantity Surveyor','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09614365687','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 11, 57)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Arnelito Cruz','email' => 'abbierichbuild78@gmail.com','gender' => 'Male','company' => 'Richbuild Construction Corporation','company_address' => 'C6 Road, Brgy. Wawa, Taguig City','position' => 'Operation Manager','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '09276604062','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 12, 13)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Julie Christie dela Cruz','email' => 'chair.founder@picqs.org','gender' => 'Female','company' => 'PICQS','company_address' => 'Makati City','position' => 'Chair and Founder','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '+639189092612','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 12, 31)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Marlene S. Martinez','email' => 'msmpicqs@yahoo.com','gender' => 'Female','company' => 'PICQS','company_address' => 'Vicente Madrigal Bldg. 6793 Ayala Ave., Makati City','position' => 'PICQS Head for TESDA','affiliation' => 'Philippine Constructors Association (PCA)','contact_number' => '+639178570819','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 12, 34)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Jessica Galitob','email' => 'galitobjessica@gmail.com','gender' => 'Female','company' => 'CIAP','company_address' => 'Executive Building Center, Makati City','position' => 'TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09755284963','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 14, 3)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Mary Anne Y. Pinlac','email' => 'maryannepinlac@construction.gov.ph','gender' => 'Female','company' => 'CIAP Executive Office','company_address' => 'No. 369 Executive Building Center, Sen. Gil J. Puyat Avenue, Makati City','position' => 'Supervising Trade-Industry Development Specialist','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09171753395','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 14, 10)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Martina Stephanie B. Macalanda','email' => 'martinamacalanda@construction.gov.ph','gender' => 'Female','company' => 'Construction Manpower Development Foundation','company_address' => '5/F 369 Executive Bldg, Sen. Gil Puyat St., Makati City','position' => 'Project Development Officer','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09178086968','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 15, 5)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Anthony Von Ryan O. Panelo','email' => 'anthonyvonryanpanelo@construction.gov.ph','gender' => 'Male','company' => 'CIAP CMDF','company_address' => '5F Executive Building Center, 369 Sen. Gil Puyat Ave., Makati City','position' => 'OIC Chief','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09662268233','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 15, 5, 19)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Maria Luisa DV. Olitoquit','email' => 'mdolitoquit.arbitrator@gmail.com','gender' => 'Female','company' => 'MLDVO Freelance Engineer and Consultant','company_address' => 'Blk 32 Lot 2 Rspiritu Street, Katarungan Village, Poblacion, Muntinlupa City','position' => 'Owner','affiliation' => 'Philippine Institute of Construction Arbitrators and Mediators (PICAM)','contact_number' => '09163095435','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 15, 10)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Jan Amiel C. de Leon','email' => 'janamieldeleon@construction.gov.ph','gender' => 'Male','company' => 'CIAP','company_address' => '5F Executive Building Center, 369 Sen. Gil Puyat Ave., Makati City','position' => 'OIC-Division Chief','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09663326841','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 16, 24)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Rosalie O. Igay','email' => 'RosalieIgay@construction.gov.ph','gender' => 'Female','company' => 'Philippine Overseas Construction Board','company_address' => 'Makati City','position' => 'Sr. Trade and Industry Development Specialist','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09058864655','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 16, 35)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Jessica Baje','email' => 'jessicabaje@construction.gov.ph','gender' => 'Female','company' => 'CIAP','company_address' => 'Makati City','position' => 'TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09452550758','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 25, 11, 18, 11)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Nikki C. Najarro','email' => 'NikkiNajarro@construction.gov.ph','gender' => 'Female','company' => 'PDCB','company_address' => 'Makati City','position' => 'STIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '00176572343','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 7, 50)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Engr.','name' => 'Jocelyn C. Carrasco','email' => 'JocelynCarrasco@construction.gov.ph','gender' => 'Female','company' => 'PDCB','company_address' => 'Makati City','position' => 'Division Chief','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '0288961801','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 7, 52)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Lorna F. Rivera','email' => 'LornaRivera@construction.gov.ph','gender' => 'Female','company' => 'Construction Industry Authority of the Philippines','company_address' => '5/F Executive Bldg. Center, No. 369 Gil Puyat Ave. cor. MakatiAve., Makati City','position' => 'Sr. Trade-Industry Development Specialist ','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09193785621','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 8, 40)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Marlon M. Cariño','email' => 'mmcarino@ust.edu.ph','gender' => 'Male','company' => 'PICAM','company_address' => 'Makati City','position' => 'Member / Arbitrator ','affiliation' => 'PICAM/ CIAC','contact_number' => '09177946439','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 8, 58)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Melanie T. Napiza','email' => 'mtnapiza@ppa.com.ph','gender' => 'Female','company' => 'Philippine Ports Authority','company_address' => 'PPA CORP. BUILDING, Bonifacio Drive, Port Area, Manila','position' => 'Principal Engineer A','affiliation' => 'Philippine Ports Authority','contact_number' => '09178052060','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 9, 35)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Geraline C. Bautista','email' => 'gcbautista@ppa.com.ph','gender' => 'Female','company' => 'Philippine Ports Authority','company_address' => 'PPA CORP. BUILDING, Bonifacio Drive, Port Area, Manila','position' => 'Principal Engineer A','affiliation' => 'Philippine Ports Authority','contact_number' => '09178620737','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 9, 42)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Tessie R. Mendoza','email' => 'TessieMendoza@construction.gov.ph','gender' => 'Female','company' => 'PCAB','company_address' => 'Makati City','position' => 'TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09178024176','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 10, 5)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'Charlie A. Barinque','email' => 'charliebarinque@construction.gov.ph','gender' => 'Male','company' => 'Construction Industry Authority of the Philippines','company_address' => 'Makati City','position' => 'Information Technology Officer','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09989557281','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 10, 23)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mrs.','name' => 'Delia B. Billedo-Perlada','email' => 'delia_perlada@yahoo.com','gender' => 'Female','company' => 'Construction Industry Arbitration Commission','company_address' => '2nd Floor Executive Building Centre, Gil Puyat cor Makati Ave., Makati City. ','position' => 'Division Chief, Arbitration Mediation Conciliation Division ','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09171421027','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 10, 35)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Mr.','name' => 'RAYMOND GARCIA','email' => 'raymondgarcia@construction.gov.ph','gender' => 'Male','company' => 'CIAP-CIAC','company_address' => '2nd Floor Executive Building Center, 369 Gil Puyat Ave. cor. Makati Ave., Makati City','position' => 'Supervising TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09178779738','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 10, 44)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'DELIA B. BILLEDO-PERLADA','email' => 'delia_perlada@yahoo.com','gender' => 'Female','company' => 'CIAP-CIAC','company_address' => '2nd Floor Executive Building Center, 369 Gil Puyat Ave. cor. Makati Ave., Makati City','position' => 'Chief TIDS','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09171421027','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 10, 52)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Atty.','name' => 'Jinky Ann Cruz','email' => 'jinkyanncruz@construction.gov.ph','gender' => 'Female','company' => 'PCAB','company_address' => 'PCAB - 5th floor, Jupiter st. Makati City','position' => 'Division Chief','affiliation' => 'Construction Industry Authority of the Philippines/Philippine Contractors Accreditation Board','contact_number' => '09985832352','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 11, 19)->format('m/d/Y H:i:s')],
            ['id' => Str::uuid()->toString(),'title' => 'Ms.','name' => 'Doris Gacho','email' => 'DorisGacho@construction.gov.ph','gender' => 'Female','company' => 'CIAP-PODCB','company_address' => '5th Flr., Executive Center Bldg., Makati Ave. Cor. Sen. Puyat, Makati City','position' => 'Executive Director','affiliation' => 'CIAP-PODCB','contact_number' => '09178796765','score' => null,'is_agree_privacy' => true,'created_at' => Carbon::create(2024, 26, 11, 12, 53)->format('m/d/Y H:i:s')]
        ];

        foreach ($registrants as $registrant) {
            Registrant::firstOrCreate(
                [
                    'email' => $registrant['email'],
                    'company' => $registrant['company']
                ],
                $registrant
            );
        }
    }
}
